name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Set deploy token
        id: set-token
        run: |
          if [ "${{ github.actor }}" == "changonna" ]; then
            echo "GH_TOKEN=${{ secrets.GH_TOKEN_CHANGONNA }}" >> $GITHUB_ENV;
          elif [ "${{ github.actor }}" == "kwonyongjun1" ]; then
            echo "GH_TOKEN=${{ secrets.GH_TOKEN_KWONYOUNGJUN1 }}" >> $GITHUB_ENV;
          else
            echo "Unknown user";
            exit 1;
          fi
      - name: Configure Git
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
